### ISSUE TITLE
graylog cannot start

### ISSUE THREAD

**Issue by rlagmlah** [KongZ/graylog-plugin-slack-notification#20]
Hello.
After adding the plugin, it can't start with the following error:

```
Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Map injection failed due to duplicated key "slack-notification-v1", from bindings:
         at org.graylog2.plugin.PluginModule.addNotificationType(PluginModule.java:301) (via modules: org.graylog2.shared.bindings.PluginBindings -> org.graylog.integrations.IntegrationsModule)
         at org.graylog2.plugin.PluginModule.addNotificationType(PluginModule.java:301) (via modules: org.graylog2.shared.bindings.PluginBindings -> com.kongz.graylog.plugins.slack.SlackNotificationPluginModule)

  at org.graylog2.plugin.PluginModule.eventNotificationBinder(PluginModule.java:293) (via modules: org.graylog.events.EventsModule -> com.google.inject.internal.RealMapBinder)

1 error
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:159)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at org.graylog2.shared.bindings.GuiceInjectorHolder.createInjector(GuiceInjectorHolder.java:34)
        at org.graylog2.bootstrap.CmdLineTool.setupInjector(CmdLineTool.java:381)
        at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:196)
        at org.graylog2.bootstrap.Main.main(Main.java:50)
```
Thanks.

**Comment by KongZ** [comment]
This repository is for Graylog 2.x and Graylog 3.0. And it is no longer maintain. 
If you are looking for newer version check out https://github.com/KongZ/graylog-plugin-slack

**Comment by KongZ** [comment]
Look like there is another graylog-plugin-slack-notification in your plugins directory

**Comment by rlagmlah** [comment]
That's weird. The plugins I have installed are:

```
graylog-plugin-aws-4.0.2.jar
graylog-plugin-collector-4.0.2.jar
graylog-plugin-integrations-4.0.2.jar
graylog-plugin-slack-3.1.0.jar
graylog-plugin-threatintel-4.0.2.jar
graylog-storage-elasticsearch6-4.0.2.jar
graylog-storage-elasticsearch7-4.0.2.jar
graylog-plugin-slack-notification-4.0.1.jar
```

Note: Of these, even if I remove the graylog-plugin-slack-3.1.0.jar the error appears.

PS: The problem occurred after I recently upgraded graylog from version 3.3.8 to 4.0.2. Is it related to this?

**Comment by canyildiz** [comment]
I'm having the same issue. This appeared after upgrading Graylog to 4.0.5. When I remove slack integration from plugin directory everything works fine. When I copy it back to plugins directory then boot begins to stuck in loop of same error message as following:
````
2021-03-22T21:37:07.529+03:00 INFO  [CmdLineTool] Loaded plugin: SlackNotification 1.0.5 [com.sportalliance.graylog.plugins.slacknotification.SlackNotificationPlugin]
2021-03-22T21:37:07.535+03:00 INFO  [CmdLineTool] Loaded plugin: AWS plugins 4.0.5 [org.graylog.aws.AWSPlugin]
2021-03-22T21:37:07.536+03:00 INFO  [CmdLineTool] Loaded plugin: Integrations 4.0.5 [org.graylog.integrations.IntegrationsPlugin]
2021-03-22T21:37:07.538+03:00 INFO  [CmdLineTool] Loaded plugin: Collector 4.0.5 [org.graylog.plugins.collector.CollectorPlugin]
2021-03-22T21:37:07.539+03:00 INFO  [CmdLineTool] Loaded plugin: Threat Intelligence Plugin 4.0.5 [org.graylog.plugins.threatintel.ThreatIntelPlugin]
2021-03-22T21:37:07.539+03:00 INFO  [CmdLineTool] Loaded plugin: Elasticsearch 6 Support 4.0.5+d95b909 [org.graylog.storage.elasticsearch6.Elasticsearch6Plugin]
2021-03-22T21:37:07.540+03:00 INFO  [CmdLineTool] Loaded plugin: Elasticsearch 7 Support 4.0.5+d95b909 [org.graylog.storage.elasticsearch7.Elasticsearch7Plugin]
2021-03-22T21:37:07.989+03:00 INFO  [CmdLineTool] Running with JVM arguments: -Xms8g -Xmx8g -XX:NewRatio=1 -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:-OmitStackTraceInFastThrow -Djdk.tls.acknowledgeCloseNotify=true -XX:+UseParNewGC -Dlog4j.configurationFile=file:///etc/graylog/server/log4j2.xml -Djava.library.path=/usr/share/graylog-server/lib/sigar -Dgraylog2.installation_source=rpm
2021-03-22T21:37:08.371+03:00 INFO  [Version] HV000001: Hibernate Validator null
2021-03-22T21:37:12.429+03:00 ERROR [CmdLineTool] Guice error (more detail on log level debug): Map injection failed due to duplicated key "slack-notification-v1", from bindings:
         at org.graylog2.plugin.PluginModule.addNotificationType(PluginModule.java:301) (via modules: org.graylog2.shared.bindings.PluginBindings -> com.sportalliance.graylog.plugins.slacknotification.SlackNotificationModule)
         at org.graylog2.plugin.PluginModule.addNotificationType(PluginModule.java:301) (via modules: org.graylog2.shared.bindings.PluginBindings -> org.graylog.integrations.IntegrationsModule)

2021-03-22T21:37:24.729+03:00 INFO  [CmdLineTool] Loaded plugin: SlackNotification 1.0.5 [com.sportalliance.graylog.plugins.slacknotification.SlackNotificationPlugin]
2021-03-22T21:37:24.734+03:00 INFO  [CmdLineTool] Loaded plugin: AWS plugins 4.0.5 [org.graylog.aws.AWSPlugin]
2021-03-22T21:37:24.736+03:00 INFO  [CmdLineTool] Loaded plugin: Integrations 4.0.5 [org.graylog.integrations.IntegrationsPlugin]
2021-03-22T21:37:24.737+03:00 INFO  [CmdLineTool] Loaded plugin: Collector 4.0.5 [org.graylog.plugins.collector.CollectorPlugin]
2021-03-22T21:37:24.739+03:00 INFO  [CmdLineTool] Loaded plugin: Threat Intelligence Plugin 4.0.5 [org.graylog.plugins.threatintel.ThreatIntelPlugin]
2021-03-22T21:37:24.739+03:00 INFO  [CmdLineTool] Loaded plugin: Elasticsearch 6 Support 4.0.5+d95b909 [org.graylog.storage.elasticsearch6.Elasticsearch6Plugin]
2021-03-22T21:37:24.740+03:00 INFO  [CmdLineTool] Loaded plugin: Elasticsearch 7 Support 4.0.5+d95b909 [org.graylog.storage.elasticsearch7.Elasticsearch7Plugin]
2021-03-22T21:37:25.203+03:00 INFO  [CmdLineTool] Running with JVM arguments: -Xms8g -Xmx8g -XX:NewRatio=1 -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:-OmitStackTraceInFastThrow -Djdk.tls.acknowledgeCloseNotify=true -XX:+UseParNewGC -Dlog4j.configurationFile=file:///etc/graylog/server/log4j2.xml -Djava.library.path=/usr/share/graylog-server/lib/sigar -Dgraylog2.installation_source=rpm
2021-03-22T21:37:25.595+03:00 INFO  [Version] HV000001: Hibernate Validator null
2021-03-22T21:37:29.608+03:00 ERROR [CmdLineTool] Guice error (more detail on log level debug): Map injection failed due to duplicated key "slack-notification-v1", from bindings:
         at org.graylog2.plugin.PluginModule.addNotificationType(PluginModule.java:301) (via modules: org.graylog2.shared.bindings.PluginBindings -> com.sportalliance.graylog.plugins.slacknotification.SlackNotificationModule)
         at org.graylog2.plugin.PluginModule.addNotificationType(PluginModule.java:301) (via modules: org.graylog2.shared.bindings.PluginBindings -> org.graylog.integrations.IntegrationsModule)
````

**Comment by canyildiz** [comment]
I solved my problem by installing following plugin. Not it works perfect1

https://github.com/graylog-labs/graylog-plugin-slack/releases/tag/3.1.0

**Comment by KongZ** [comment]
@canyildiz your Graylog contains `SlackNotification 1.0.5 [com.sportalliance.graylog.plugins.slacknotification.SlackNotificationPlugin]` which accidently using same plugin ID

You have to remove `com.sportalliance.graylog.plugins.slacknotification.SlackNotificationPlugin` to avoid plugin conflict.

**Comment by KongZ** [comment]
@rlagmlah your Graylog also contains `graylog-plugin-slack-3.1.0.jar`
It is using same plugin ID. We can't use same plugin ID at the same time.

**Comment by canyildiz** [comment]
> @canyildiz your Graylog contains `SlackNotification 1.0.5 [com.sportalliance.graylog.plugins.slacknotification.SlackNotificationPlugin]` which accidently using same plugin ID
> 
> You have to remove `com.sportalliance.graylog.plugins.slacknotification.SlackNotificationPlugin` to avoid plugin conflict.

I had written that Graylog included Slack notification plugin built-in beginning from version 4.0 . Is it possible this plugin you pointed is the one included in Graylog? Because I hadn't install any plugin about Slack before yours.

**Comment by KongZ** [comment]
@canyildiz no, the [sportalliance](https://github.com/sportalliance/graylog-plugin-slack-notification) is external plugin. The graylog does not ship with any Slack plugins.

**Comment by rlagmlah** [comment]
you are right. graylog-plugin-integrations included slack notifications.
